torchrun --nproc_per_node=1 ./src/train_model.py --enable_distributed --use_amp --amp_dtype bfloat16 --model cnn --dataset_name mnist --max_epochs 500 --pretrained_model_path ./output/final_model.pth --dataset_dir /media/horizon/Database/robotic_datasets/visual_learning
# torchrun --nproc_per_node=1 ./src/train_model.py --enable_distributed --use_amp --amp_dtype bfloat16 --model mlp --dataset_name mnist --max_epochs 500 --pretrained_model_path ./output/final_model.pth --dataset_dir /media/horizon/Database/robotic_datasets/visual_learning
# torchrun --nproc_per_node=1 ./src/train_model.py --enable_distributed --use_amp --amp_dtype bfloat16 --model resnet --dataset_name mnist --max_epochs 500 --pretrained_model_path ./output/final_model.pth --dataset_dir /media/horizon/Database/robotic_datasets/visual_learning
# torchrun --nproc_per_node=1 ./src/train_model.py --enable_distributed --use_amp --amp_dtype bfloat16 --model vit --dataset_name mnist --max_epochs 500 --pretrained_model_path ./output/final_model.pth --dataset_dir /media/horizon/Database/robotic_datasets/visual_learning

# torchrun --nproc_per_node=1 ./src/train_model.py --enable_distributed --use_amp --amp_dtype bfloat16 --model cnn --dataset_name cifar10 --max_epochs 500 --pretrained_model_path ./output/final_model.pth --dataset_dir /media/horizon/Database/robotic_datasets/visual_learning
# torchrun --nproc_per_node=1 ./src/train_model.py --enable_distributed --use_amp --amp_dtype bfloat16 --model mlp --dataset_name cifar10 --max_epochs 500 --pretrained_model_path ./output/final_model.pth --dataset_dir /media/horizon/Database/robotic_datasets/visual_learning
# torchrun --nproc_per_node=1 ./src/train_model.py --enable_distributed --use_amp --amp_dtype bfloat16 --model resnet --dataset_name cifar10 --max_epochs 500 --pretrained_model_path ./output/final_model.pth --dataset_dir /media/horizon/Database/robotic_datasets/visual_learning
# torchrun --nproc_per_node=1 ./src/train_model.py --enable_distributed --use_amp --amp_dtype bfloat16 --model vit --dataset_name cifar10 --max_epochs 500 --pretrained_model_path ./output/final_model.pth --dataset_dir /media/horizon/Database/robotic_datasets/visual_learning
